version: "3"
services:
  db:
    container_name: oakcrime.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oakcrime
    image: mdillon/postgis:11
    volumes:
      - db-data:/var/lib/postgresql/data
    # NOTE: If you need to access the database from an external tool,
    # expose this port and restart the container.
    # ports:
    #   - 5432:5432
    restart: always
  app:
    depends_on:
      - db

    links:
      - db
    ports:
      # This port is primarily exposed for debugging. Use the web service's port to properly access the service.
      - 8000:8000
    volumes:
      - .:/app/showCrime:cached
volumes:
  db-data:
