version: "3"
services:
  db:
    container_name: oakcrime.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oakcrime
    image: mdillon/postgis:11
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro

      - ./data:/docker-entrypoint-initdb.d
    # NOTE: If you need to access the database from an external tool,
    # expose this port and restart the container.
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Instruct Gunicorn to reload code when it is changed locally.
    command: >-
      gunicorn showCrime.wsgi
        --workers=2
        --worker-class=gevent
        --bind=0.0.0.0:8000
        --log-file=/logs/gunicorn.log
        --reload
    container_name: oakcrime.app
    depends_on:
      - db
    links:
      - db
    environment:
      - DEBUG=true
      - SECRET_KEY=replace-me
      - DATABASE_URL=postgis://postgres:postgres@oakcrime.db:5432/oakcrime?connect_timeout=60
      - DEFAULT_FILE_STORAGE=django.core.files.storage.FileSystemStorage
      - SERVER_EMAIL=root@localhost
      - EMAIL_URL=smtp://user@:password@localhost:25
    image: openoakland/oakcrime:latest
    stdin_open: true
    tty: true
    ports:
      # This port is primarily exposed for debugging. Use the web service's port to properly access the service.
      - 8000:8000
    volumes:
      - .:/app/showCrime:cached
      - logs:/logs
      - media:/public/media/
      - static:/public/static/
  web:
    container_name: oakcrime.web
    image: nginx:1.15-alpine
    depends_on:
      - app
    links:
      - app
    ports:
      - 8080:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - logs:/var/log/nginx
      - media:/public/media:ro
      - static:/public/static:ro
volumes:
  db-data:
  db-init:
  logs:
  media:
  static:
