version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oakcrime.app
    image: openoakland/oakcrime:latest
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - logs:/logs
      - media:/public/media/
      - static:/public/static/
  web:
    container_name: oakcrime.web
    image: nginx:1.15-alpine
    links:
      - app
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - logs:/var/log/nginx
      - media:/public/media:ro
      - static:/public/static:ro
      
  rabbitmq:
    image: "rabbitmq:3.7.14"

  celery:
    build: .
    command: celery -A showCrime.celery worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
  celery-beat:
    build: .
    command: celery -A showCrime.celery beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - rabbitmq

volumes:
  logs:
  media:
  static:
